update docker connection

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -65,7 +65,7 @@ jobs:
 
             # Verify if the deployment is successful by checking if the application responds on port 5000
             echo "Verifying deployment by checking port 5000..."
-            curl --fail http://localhost:5000 || { echo "Deployment failed"; exit 1; }
+            curl --silent --fail http://localhost:5000 || { echo "Deployment failed"; exit 1; }
             
             echo "Deployment successful!"
 
